version: 0.2

env:
  variables:
    CI: "true"
    # 必要ならテスト対象URLをここで渡す（あとで設定してOK）
    # BASE_URL: "https://stg.example.com"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v
      - npm ci
      - npx playwright install --with-deps
  build:
    commands:
      - npx playwright test

artifacts:
  files:
    - playwright-report/**/*
    - test-results/**/*
  discard-paths: no
  