version: 0.2

env:
  variables:
    CI: "true"
    # BASE_URL: "https://stg.example.com"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v
      - npm ci
      - npx playwright install --with-deps

  build:
    commands:
      - set +e
      - npx playwright test
      - "TEST_EXIT_CODE=$?"
      - "echo Playwright exit code: ${TEST_EXIT_CODE}"

      - ls -la
      - ls -la playwright-report || true
      - ls -la test-results || true

      - aws s3 sync playwright-report "s3://playwright-e2e-bucket/playwright-report/${CODEBUILD_BUILD_ID}/" --delete
      - aws s3 sync test-results "s3://playwright-e2e-bucket/test-results/${CODEBUILD_BUILD_ID}/" --delete || true

      - aws s3 sync playwright-report "s3://playwright-e2e-bucket/playwright-report/latest/" --delete
      - aws s3 sync test-results "s3://playwright-e2e-bucket/test-results/latest/" --delete || true

      - exit ${TEST_EXIT_CODE}