version: 0.2

env:
  variables:
    CI: "true"
    # 必要ならテスト対象URLをここで渡す（あとで設定してOK）
    # BASE_URL: "https://stg.example.com"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v
      - npm ci
      - npx playwright install --with-deps

  build:
    commands:
      - npx playwright test
      - aws s3 sync playwright-report "s3://playwright-e2e-bucket/playwright-report/$CODEBUILD_BUILD_ID/" --delete
      - aws s3 sync test-results "s3://playwright-e2e-bucket/test-results/$CODEBUILD_BUILD_ID/" --delete || true
      - aws s3 sync playwright-report "s3://playwright-e2e-bucket/playwright-report/latest/" --delete

artifacts:
  files:
    - playwright-report/**/*
    - test-results/**/*
  discard-paths: no
  