version: 0.2

env:
  variables:
    CI: "true"
    # 必要ならテスト対象URLをここで渡す（あとで設定してOK）
    # BASE_URL: "https://stg.example.com"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v
      - npm ci
      - npx playwright install --with-deps

      - echo "=== STS caller identity ==="
      - aws sts get-caller-identity
      - echo "=== S3 write test ==="
      - echo ok > /tmp/cb_s3_test.txt
      - aws s3 cp /tmp/cb_s3_test.txt s3://playwright-e2e-bucket/_codebuild_write_test/$CODEBUILD_BUILD_ID.txt

  build:
    commands:
      - npx playwright test

artifacts:
  files:
    - playwright-report/**/*
    - test-results/**/*
  discard-paths: no
  